sudo: false
language: ruby
matrix:
  include:
    - rvm: 2.1
      gemfile: gemfiles/rails4.1.gemfile
    - rvm: 2.1
      gemfile: gemfiles/rails4.2.gemfile
    - rvm: 2.0
      gemfile: gemfiles/rails4.2.gemfile
    - rvm: jruby-19mode
      gemfile: gemfiles/rails4.2.gemfile
